### ISSUE TITLE
Got "Permission denied" without log

### ISSUE THREAD

**Issue by yakira-neko** [sourcetoad/tizen-build-action#15]
Here is what I got :![Screenshot_2024-03-03-18-37-27-515_com github android](https://github.com/sourcetoad/tizen-build-action/assets/47704813/81d37490-5115-49d8-8518-bd52e717bc5e)
My actions file:https://github.com/someone120/tizen_novel/blob/main/.github/workflows/auto-build.yml

**Comment by yakira-neko** [comment]
Fix after changed to latest version.

**Comment by iBotPeaches** [comment]
ah cool, I was checking if the file was +x chmod and it was. Glad it's working.
